config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create, :edit, :update,:destroy, :show] 
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :subs
  resources :users
  resource :session, only: [:new, :create, :destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :author, class_name: "User"
  belongs_to :parent_comment, class_name: "Comment"
  has_many :child_comments, class_name: "Comment",
    foreign_key: :parent_comment_id
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :check_for_user, only: [:new, :create]
  before_action :check_for_author, only: [:update, :edit, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user

    if @comment.save
      redirect_to @comment.post
    else
      render :edit
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :author_id, :content, :parent_comment_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% child_comments = @all_comments.select do |comment2| %>
  <% comment2.parent_comment_id == comment.id if comment2.parent_comment_id %>
<% end %>

<a href="<%= comment_url(comment) %>"><%= "#{comment.author.email} says: #{comment.content}" %></a>
<% child_comments.each do |child_comment| %>
 <ul>
   <li>
     <%= render child_comment %>
   </li>
</ul>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :author_id %><br>
    <%= f.number_field :author_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<form class="" action="<%= comments_url %>" method="post">
  <input type="hidden" name="comment[post_id]" value="<%= params[:post_id] %>">
  <%= csrf_html %>
  <textarea name="comment[content]" rows="8" cols="40"></textarea>
<input type="submit">

</form>

app/views/comments/show.html.erb
<h2>Comment for <%= @comment.post.title %> </h2>

<p>
  <%= @comment.content %>
</p>

<p>
  New Comment:
</p>

<form action="<%= comments_url %>" method="post">
  <%= csrf_html %>
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id%>">
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">
  <textarea name="comment[content]" rows="8" cols="40"></textarea>
  <input type="submit"  value="submit comment">
</form>