config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create, :edit, :update,:destroy, :show] 
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :subs
  resources :users
  resource :session, only: [:new, :create, :destroy]

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :author_id, :post_subs, presence: true

  has_many :post_subs, inverse_of: :post
  has_many :subs, through: :post_subs, source: :sub

  belongs_to :author, class_name: "User"

  has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :check_for_user, only: [:new, :create]
  before_action :check_for_author, only: [:update, :edit, :destroy]

  # GET /posts/1
  # GET /posts/1.json
  def show
    @all_comments = @post.comments.includes(:author)
    @parent_comments = @all_comments.select do |comment|
      comment.parent_comment_id.nil?
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.author = current_user
    if @post.save
      redirect_to @post
    else
      flash[:error] = "Something went terribly wrong"
      render :new
    end

  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post.update(post_params)
    if @post.save
      flash[:success] = "Post updated!"
      redirect_to @post
    else
      flash[:error] = "Something went terribly wrong"
      render :edit
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    redirect_to subs_url, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :url, :content, :author_id, sub_ids: [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<form action="<%= @post.persisted? ? post_url(@post) : posts_url %>" method="post">
  <%= csrf_html %>

  <% if @post.persisted? %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <label for="post_title">Title</label>
  <input type="text" name="post[title]" value="<%= @post.title %>">
  <br>

  <label for="post_url">URL</label>
  <input type="text" name="post[url]" value="<%= @post.url %>">
  <br>

  <label for="post_content">Content</label>
  <textarea name="post[content]"
  rows="8"
  cols="40"><%= @post.content %></textarea>
  <br>

  <label>
    <% Sub.all.each do |sub| %>
      <input name="post[sub_ids][]" value="<%= sub.id %>" type="checkbox"
        <%= @post.subs.map(&:id).include?(sub.id) ? "checked" : "" %>>
        <%= sub.name %>
      </input>
    <% end %>
  </label>

  <input type="submit">
</form>

app/views/posts/_post.html.erb
<li>
  <a href="<%= post_url(post) %>"><%= post.title %></a>
</li>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @post.url %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Sub:</strong>
  <%= @post.subs.map(&:title).join(', ') %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.author.email %>
</p>

<a href="<%= new_post_comment_url(@post) %>">New comment</a>


<ol>
  <% @parent_comments.each do |comment| %>
    <li>
     <%= render 'comments/comment', comment: comment %>
    </li>
  <% end %>
</ol>